# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/google/modules/setup-makefiles.sh

PRODUCT_SOONG_NAMESPACES += \
    vendor/google/modules

PRODUCT_COPY_FILES += \
    vendor/google/modules/proprietary/product/etc/sysconfig/GoogleCellBroadcast_config.xml:$(TARGET_COPY_OUT_PRODUCT)/etc/sysconfig/GoogleCellBroadcast_config.xml \
    vendor/google/modules/proprietary/product/etc/sysconfig/google-staged-installer-whitelist.xml:$(TARGET_COPY_OUT_PRODUCT)/etc/sysconfig/google-staged-installer-whitelist.xml \
    vendor/google/modules/proprietary/system/etc/permissions/GoogleDocumentsUI_permissions.xml:$(TARGET_COPY_OUT_SYSTEM)/etc/permissions/GoogleDocumentsUI_permissions.xml \
    vendor/google/modules/proprietary/system/etc/permissions/GoogleNetworkStack_permissions.xml:$(TARGET_COPY_OUT_SYSTEM)/etc/permissions/GoogleNetworkStack_permissions.xml \
    vendor/google/modules/proprietary/system/etc/sysconfig/preinstalled-packages-com.google.android.providers.media.module.xml:$(TARGET_COPY_OUT_SYSTEM)/etc/sysconfig/preinstalled-packages-com.google.android.providers.media.module.xml

PRODUCT_PACKAGES += \
    com.google.android.adbd_compressed \
    com.google.android.adservices_compressed \
    com.google.android.appsearch_compressed \
    com.google.android.art_compressed \
    com.google.android.cellbroadcast_compressed \
    com.google.android.configinfrastructure_compressed \
    com.google.android.conscrypt_compressed \
    com.google.android.extservices_compressed \
    com.google.android.healthfitness_compressed \
    com.google.android.ipsec_compressed \
    com.google.android.media.swcodec_compressed \
    com.google.android.media_compressed \
    com.google.android.mediaprovider_compressed \
    com.google.android.neuralnetworks_compressed \
    com.google.android.ondevicepersonalization_compressed \
    com.google.android.os.statsd_compressed \
    com.google.android.permission_compressed \
    com.google.android.resolv_compressed \
    com.google.android.scheduling_compressed \
    com.google.android.sdkext_compressed \
    com.google.android.tethering_compressed \
    com.google.android.tzdata5 \
    com.google.android.wifi_compressed \
    com.google.mainline.primary.libs \
    CaptivePortalLoginGoogle-hdpi \
    CaptivePortalLoginGoogle-ldpi \
    CaptivePortalLoginGoogle-mdpi \
    CaptivePortalLoginGoogle-tvdpi \
    CaptivePortalLoginGoogle-xhdpi \
    CaptivePortalLoginGoogle-xxhdpi \
    CaptivePortalLoginGoogle-xxxhdpi \
    CaptivePortalLoginGoogle \
    DocumentsUIGoogle-hdpi \
    DocumentsUIGoogle-ldpi \
    DocumentsUIGoogle-mdpi \
    DocumentsUIGoogle-tvdpi \
    DocumentsUIGoogle-xhdpi \
    DocumentsUIGoogle-xxhdpi \
    DocumentsUIGoogle-xxxhdpi \
    DocumentsUIGoogle \
    NetworkStackGoogle-arm64_v8a \
    NetworkStackGoogle-hdpi \
    NetworkStackGoogle-ldpi \
    NetworkStackGoogle-mdpi \
    NetworkStackGoogle-tvdpi \
    NetworkStackGoogle-xhdpi \
    NetworkStackGoogle-xxhdpi \
    NetworkStackGoogle-xxxhdpi \
    NetworkStackGoogle \
    com.google.android.modulemetadata \
    com.google.mainline.adservices \
    com.google.mainline.telemetry
